# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Windsor Rocker Company
tagline: Tradition evolved
email: info@windsorrocker.com
description: The Windsor Rocker Company - makers of Katie Walker's famous Windsor Rocker.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.windsorrocker.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  windsorrocker
creator: windsorrocker
author:
  name: Roland Whitehead
  url: https://cart-shed.com
  email: roland@cart-shed.com    
# Build settings
author:
  name: Roland Whitehead
  url: https://cart-shed.com
  email: roland@cart-shed.com
pages_list:
  About: '/about'
  Feet: '/atom.xml'
exclude:
  - '.#*'
  - '/*/.#*'
  - '#*'
  - '/*/#*'
  - 'links/*'
  - 'static/style/#*'
  - 'static/style/.#*'
  - 'static/js/#*'
  - 'static/js/.#*'
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
version: 0.1
kramdown:
  gfm_quirks: [paragraph_end]
  gfm_emojis: true
  hard_wrap: true# Exclude from processing.
