title: Windsor Rocker Company
tagline: Tradition evolved
email: info@windsorrocker.com
description: "The Windsor Rocker Company - makers of Katie Walker's famous Windsor Rocker."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.windsorrocker.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  windsorrocker
creator: windsorrocker
author:
  name: Roland Whitehead
  url: https://cart-shed.com
  email: roland@cart-shed.com
pages_list:
  About: '/about'
  Feet: '/atom.xml'
exclude:
  - '.#*'
  - '/*/.#*'
  - '#*'
  - '/*/#*'
  - 'links/*'
  - 'static/style/#*'
  - 'static/style/.#*'
  - 'static/js/#*'
  - 'static/js/.#*'
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
version: 0.1
kramdown:
  gfm_quirks: [paragraph_end]
  gfm_emojis: true
  hard_wrap: true
collections:
    gallery:
        output: true
